# Generated by Django 5.1.7 on 2026-02-14 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gtdclassificationpattern',
            options={'verbose_name': 'GTD Classification Pattern', 'verbose_name_plural': 'GTD Classification Patterns'},
        ),
        migrations.AlterModelOptions(
            name='gtdlearningentry',
            options={'verbose_name': 'GTD Learning Entry', 'verbose_name_plural': 'GTD Learning Entries'},
        ),
        migrations.AlterModelOptions(
            name='gtdprocessingsettings',
            options={'ordering': ['-updated_at'], 'verbose_name': 'GTD Processing Settings', 'verbose_name_plural': 'GTD Processing Settings'},
        ),
        migrations.AlterModelOptions(
            name='taskschedule',
            options={'ordering': ['start_time'], 'verbose_name': 'Task Schedule', 'verbose_name_plural': 'Task Schedules'},
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='action_type',
            field=models.CharField(choices=[('do', 'Do'), ('delegate', 'Delegate'), ('defer', 'Defer'), ('project', 'Convert to Project'), ('delete', 'Delete'), ('archive', 'Archive for Reference'), ('incubate', 'Incubate (Someday/Maybe)'), ('waiting', 'Waiting For')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='confidence_score',
            field=models.IntegerField(default=70, help_text='Confidence level (0-100%)'),
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='description',
            field=models.TextField(help_text='Description of when to apply this pattern'),
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='energy_required',
            field=models.CharField(choices=[('low', 'Low Energy'), ('medium', 'Medium Energy'), ('high', 'High Energy')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='gtd_category',
            field=models.CharField(choices=[('actionable', 'Actionable'), ('non_actionable', 'Non Actionable'), ('pending', 'Pending Categorization')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='keywords',
            field=models.JSONField(help_text='List of keywords that trigger this pattern'),
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='keywords_operator',
            field=models.CharField(choices=[('AND', 'All keywords'), ('OR', 'Any keyword'), ('NOT', 'None of the keywords')], default='OR', max_length=10),
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='name',
            field=models.CharField(help_text='Descriptive pattern name', max_length=100),
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='Times this pattern has been used'),
        ),
        migrations.AlterField(
            model_name='gtdlearningentry',
            name='was_correct',
            field=models.BooleanField(default=False, help_text='Was the prediction correct?'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='auto_call_queue',
            field=models.BooleanField(default=True, help_text='Automatic call queue'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='auto_chat_routing',
            field=models.BooleanField(default=True, help_text='Automatic chat routing'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='auto_email_processing',
            field=models.BooleanField(default=True, help_text='Automatic email processing'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='auto_priority_assignment',
            field=models.BooleanField(default=True, help_text='Automatic priority assignment'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='call_queue_timeout',
            field=models.IntegerField(default=30, help_text='Call queue timeout in seconds'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='chat_response_timeout',
            field=models.IntegerField(default=300, help_text='Chat response timeout in seconds'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='email_batch_size',
            field=models.IntegerField(default=10, help_text='Email batch size'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='enable_bot_atc',
            field=models.BooleanField(default=True, help_text='Enable Bot ATC'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='enable_bot_cx',
            field=models.BooleanField(default=True, help_text='Enable Bot CX'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='enable_human_agents',
            field=models.BooleanField(default=True, help_text='Enable human agents'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active configuration'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='max_concurrent_items',
            field=models.IntegerField(default=5, help_text='Maximum concurrent items'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='priority_threshold_high',
            field=models.IntegerField(default=80, help_text='High priority threshold'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='priority_threshold_medium',
            field=models.IntegerField(default=50, help_text='Medium priority threshold'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='processing_interval',
            field=models.IntegerField(default=60, help_text='Processing interval in seconds'),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='action_type',
            field=models.CharField(blank=True, choices=[('do', 'Do'), ('delegate', 'Delegate'), ('defer', 'Defer'), ('project', 'Convert to Project'), ('delete', 'Delete'), ('archive', 'Archive for Reference'), ('incubate', 'Incubate (Someday/Maybe)'), ('waiting', 'Waiting For')], help_text='Specific action type', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User assigned to process this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inbox_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, help_text='Users authorized to view and classify this item', related_name='authorized_inbox_items', through='events.InboxItemAuthorization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='classification_votes',
            field=models.ManyToManyField(blank=True, help_text='Users who have voted on classification', related_name='classified_inbox_items', through='events.InboxItemClassification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='context',
            field=models.CharField(blank=True, help_text='Context where this can be done (e.g., @home, @work, @phone)', max_length=50),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='created_during',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (6-12)'), ('afternoon', 'Afternoon (12-18)'), ('evening', 'Evening (18-24)'), ('night', 'Night (0-6)')], help_text='Creation time period for pattern analysis', max_length=20),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Due date if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='energy_required',
            field=models.CharField(choices=[('low', 'Low Energy'), ('medium', 'Medium Energy'), ('high', 'High Energy')], default='medium', help_text='Required mental energy level', max_length=20),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='estimated_time',
            field=models.IntegerField(blank=True, help_text='Estimated time in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='gtd_category',
            field=models.CharField(choices=[('actionable', 'Actionable'), ('non_actionable', 'Non Actionable'), ('pending', 'Pending Categorization')], default='pending', help_text='Main GTD categorization', max_length=20),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Can be viewed by other users?'),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='next_review_date',
            field=models.DateTimeField(blank=True, help_text='Next review date', null=True),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional processing notes'),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Item priority', max_length=10),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Previous review notes'),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='user_context',
            field=models.JSONField(blank=True, help_text='Custom user context', null=True),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times viewed'),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='waiting_for',
            field=models.TextField(blank=True, help_text='What is being waited for? (e.g., client response)'),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='waiting_for_date',
            field=models.DateTimeField(blank=True, help_text='Expected response date', null=True),
        ),
        migrations.AlterField(
            model_name='inboxitemauthorization',
            name='permission_level',
            field=models.CharField(choices=[('view', 'View Only'), ('classify', 'View and Classify'), ('edit', 'View, Classify and Edit'), ('admin', 'Full Admin')], default='classify', max_length=20),
        ),
        migrations.AlterField(
            model_name='inboxitemclassification',
            name='action_type',
            field=models.CharField(blank=True, choices=[('do', 'Do'), ('delegate', 'Delegate'), ('defer', 'Defer'), ('project', 'Convert to Project'), ('delete', 'Delete'), ('archive', 'Archive for Reference'), ('incubate', 'Incubate (Someday/Maybe)'), ('waiting', 'Waiting For')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inboxitemclassification',
            name='confidence',
            field=models.IntegerField(default=50, help_text='Confidence level in classification (0-100%)'),
        ),
        migrations.AlterField(
            model_name='inboxitemclassification',
            name='gtd_category',
            field=models.CharField(choices=[('actionable', 'Actionable'), ('non_actionable', 'Non Actionable'), ('pending', 'Pending Categorization')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inboxitemclassification',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about classification'),
        ),
        migrations.AlterField(
            model_name='inboxitemclassification',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='inboxitemhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('viewed', 'Viewed'), ('classified', 'Classified'), ('edited', 'Edited'), ('processed', 'Processed'), ('shared', 'Shared'), ('authorized', 'Authorization Changed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inboxitemhistory',
            name='new_values',
            field=models.JSONField(blank=True, help_text='New values', null=True),
        ),
        migrations.AlterField(
            model_name='inboxitemhistory',
            name='old_values',
            field=models.JSONField(blank=True, help_text='Previous values', null=True),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='estimated_duration',
            field=models.IntegerField(help_text='Duration in days'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('both', 'Email and Push')], max_length=20),
        ),
        migrations.AlterField(
            model_name='taskdependency',
            name='dependency_type',
            field=models.CharField(choices=[('finish_to_start', 'Finish to Start'), ('start_to_start', 'Start to Start'), ('finish_to_finish', 'Finish to Finish'), ('start_to_finish', 'Start to Finish')], max_length=20),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='recurrence_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('daily', 'Daily'), ('custom', 'Custom')], default='weekly', max_length=20),
        ),
    ]
