# Generated by Django 5.0.4 on 2024-05-04 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tittle',
            new_name='title',
        ),
    ]
