# Generated by Django 5.1.7 on 2026-03-17 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_gtdclassificationpattern_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gtdclassificationpattern',
            options={'verbose_name': 'Patrón de Clasificación GTD', 'verbose_name_plural': 'Patrones de Clasificación GTD'},
        ),
        migrations.AlterModelOptions(
            name='gtdlearningentry',
            options={'verbose_name': 'Entrada de Aprendizaje GTD', 'verbose_name_plural': 'Entradas de Aprendizaje GTD'},
        ),
        migrations.AlterModelOptions(
            name='gtdprocessingsettings',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Configuración de Procesamiento GTD', 'verbose_name_plural': 'Configuraciones de Procesamiento GTD'},
        ),
        migrations.AlterModelOptions(
            name='taskschedule',
            options={'ordering': ['start_time'], 'verbose_name': 'Programación de Tarea', 'verbose_name_plural': 'Programaciones de Tareas'},
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='action_type',
            field=models.CharField(choices=[('hacer', 'Hacer'), ('delegar', 'Delegar'), ('posponer', 'Posponer'), ('proyecto', 'Convertir en Proyecto'), ('eliminar', 'Eliminar'), ('archivar', 'Archivar para Referencia'), ('incubar', 'Incubar (Algún Día)'), ('esperar', 'Esperar Más Información')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='confidence_score',
            field=models.IntegerField(default=70, help_text='Nivel de confianza (0-100%)'),
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='description',
            field=models.TextField(help_text='Descripción de cuándo aplicar este patrón'),
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='energy_required',
            field=models.CharField(choices=[('baja', 'Baja Energía'), ('media', 'Media Energía'), ('alta', 'Alta Energía')], default='media', max_length=20),
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='gtd_category',
            field=models.CharField(choices=[('accionable', 'Accionable'), ('no_accionable', 'No Accionable'), ('pendiente', 'Pendiente de Categorizar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='keywords',
            field=models.JSONField(help_text='Lista de palabras clave que activan este patrón'),
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='keywords_operator',
            field=models.CharField(choices=[('AND', 'Todas las palabras'), ('OR', 'Cualquier palabra'), ('NOT', 'Ninguna de las palabras')], default='OR', max_length=10),
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='name',
            field=models.CharField(help_text='Nombre descriptivo del patrón', max_length=100),
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='priority',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='gtdclassificationpattern',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='Veces que se ha usado este patrón'),
        ),
        migrations.AlterField(
            model_name='gtdlearningentry',
            name='was_correct',
            field=models.BooleanField(default=False, help_text='¿La predicción fue correcta?'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='auto_call_queue',
            field=models.BooleanField(default=True, help_text='Cola automática de llamadas'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='auto_chat_routing',
            field=models.BooleanField(default=True, help_text='Enrutamiento automático de chats'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='auto_email_processing',
            field=models.BooleanField(default=True, help_text='Procesamiento automático de emails'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='auto_priority_assignment',
            field=models.BooleanField(default=True, help_text='Asignación automática de prioridades'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='call_queue_timeout',
            field=models.IntegerField(default=30, help_text='Timeout de cola de llamadas en segundos'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='chat_response_timeout',
            field=models.IntegerField(default=300, help_text='Timeout de respuesta de chat en segundos'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='email_batch_size',
            field=models.IntegerField(default=10, help_text='Tamaño del lote de emails'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='enable_bot_atc',
            field=models.BooleanField(default=True, help_text='Habilitar Bot ATC'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='enable_bot_cx',
            field=models.BooleanField(default=True, help_text='Habilitar Bot CX'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='enable_human_agents',
            field=models.BooleanField(default=True, help_text='Habilitar agentes humanos'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Configuración activa'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='max_concurrent_items',
            field=models.IntegerField(default=5, help_text='Máximo de items concurrentes'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='priority_threshold_high',
            field=models.IntegerField(default=80, help_text='Umbral para prioridad alta'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='priority_threshold_medium',
            field=models.IntegerField(default=50, help_text='Umbral para prioridad media'),
        ),
        migrations.AlterField(
            model_name='gtdprocessingsettings',
            name='processing_interval',
            field=models.IntegerField(default=60, help_text='Intervalo de procesamiento en segundos'),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='action_type',
            field=models.CharField(blank=True, choices=[('hacer', 'Hacer'), ('delegar', 'Delegar'), ('posponer', 'Posponer'), ('proyecto', 'Convertir en Proyecto'), ('eliminar', 'Eliminar'), ('archivar', 'Archivar para Referencia'), ('incubar', 'Incubar (Algún Día)'), ('esperar', 'Esperar Más Información')], help_text='Tipo de acción específica', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Usuario asignado para procesar este item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inbox_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, help_text='Usuarios autorizados para ver y clasificar este item', related_name='authorized_inbox_items', through='events.InboxItemAuthorization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='classification_votes',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que han votado en la clasificación', related_name='classified_inbox_items', through='events.InboxItemClassification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='context',
            field=models.CharField(blank=True, help_text='Contexto donde se puede ejecutar (ej: @casa, @trabajo, @teléfono)', max_length=50),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='created_during',
            field=models.CharField(blank=True, choices=[('morning', 'Mañana (6-12)'), ('afternoon', 'Tarde (12-18)'), ('evening', 'Noche (18-24)'), ('night', 'Madrugada (0-6)')], help_text='Horario de creación para análisis de patrones', max_length=20),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Fecha límite si aplica', null=True),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='energy_required',
            field=models.CharField(choices=[('baja', 'Baja Energía'), ('media', 'Media Energía'), ('alta', 'Alta Energía')], default='media', help_text='Nivel de energía mental requerido', max_length=20),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='estimated_time',
            field=models.IntegerField(blank=True, help_text='Tiempo estimado en minutos', null=True),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='gtd_category',
            field=models.CharField(choices=[('accionable', 'Accionable'), ('no_accionable', 'No Accionable'), ('pendiente', 'Pendiente de Categorizar')], default='pendiente', help_text='Categorización GTD principal', max_length=20),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='is_public',
            field=models.BooleanField(default=False, help_text='¿Puede ser visto por otros usuarios?'),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='next_review_date',
            field=models.DateTimeField(blank=True, help_text='Próxima fecha de revisión', null=True),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas adicionales para el procesamiento'),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='priority',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', help_text='Prioridad del item', max_length=10),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Notas de revisiones anteriores'),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='user_context',
            field=models.JSONField(blank=True, help_text='Contexto personalizado del usuario', null=True),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de veces que ha sido visto'),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='waiting_for',
            field=models.TextField(blank=True, help_text='¿Qué se está esperando? (ej: respuesta de cliente)'),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='waiting_for_date',
            field=models.DateTimeField(blank=True, help_text='Fecha esperada de respuesta', null=True),
        ),
        migrations.AlterField(
            model_name='inboxitemauthorization',
            name='permission_level',
            field=models.CharField(choices=[('view', 'Solo Vista'), ('classify', 'Vista y Clasificación'), ('edit', 'Vista, Clasificación y Edición'), ('admin', 'Administrador Completo')], default='classify', max_length=20),
        ),
        migrations.AlterField(
            model_name='inboxitemclassification',
            name='action_type',
            field=models.CharField(blank=True, choices=[('hacer', 'Hacer'), ('delegar', 'Delegar'), ('posponer', 'Posponer'), ('proyecto', 'Convertir en Proyecto'), ('eliminar', 'Eliminar'), ('archivar', 'Archivar para Referencia'), ('incubar', 'Incubar (Algún Día)'), ('esperar', 'Esperar Más Información')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inboxitemclassification',
            name='confidence',
            field=models.IntegerField(default=50, help_text='Nivel de confianza en la clasificación (0-100%)'),
        ),
        migrations.AlterField(
            model_name='inboxitemclassification',
            name='gtd_category',
            field=models.CharField(choices=[('accionable', 'Accionable'), ('no_accionable', 'No Accionable'), ('pendiente', 'Pendiente de Categorizar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inboxitemclassification',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas sobre la clasificación'),
        ),
        migrations.AlterField(
            model_name='inboxitemclassification',
            name='priority',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='inboxitemhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Creado'), ('viewed', 'Visto'), ('classified', 'Clasificado'), ('edited', 'Editado'), ('processed', 'Procesado'), ('shared', 'Compartido'), ('authorized', 'Autorización Cambiada')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inboxitemhistory',
            name='new_values',
            field=models.JSONField(blank=True, help_text='Nuevos valores', null=True),
        ),
        migrations.AlterField(
            model_name='inboxitemhistory',
            name='old_values',
            field=models.JSONField(blank=True, help_text='Valores anteriores', null=True),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='estimated_duration',
            field=models.IntegerField(help_text='Duración en días'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('both', 'Email y Push')], max_length=20),
        ),
        migrations.AlterField(
            model_name='taskdependency',
            name='dependency_type',
            field=models.CharField(choices=[('finish_to_start', 'Finalizar para comenzar'), ('start_to_start', 'Comenzar para comenzar'), ('finish_to_finish', 'Finalizar para finalizar'), ('start_to_finish', 'Comenzar para finalizar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='recurrence_type',
            field=models.CharField(choices=[('weekly', 'Semanal'), ('daily', 'Diaria'), ('custom', 'Personalizada')], default='weekly', max_length=20),
        ),
    ]
