# Generated by Django 5.1.7 on 2026-05-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_message_room_remove_message_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
