# Generated by Django 5.0.4 on 2024-05-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0018_alter_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
