# Generated by Django 5.0.4 on 2024-05-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0027_alter_event_event_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estado',
            new_name='Status',
        ),
    ]
