# Generated by Django 5.0.4 on 2024-06-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0032_status_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='icon',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
