# Generated by Django 5.0.4 on 2024-06-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0039_alter_task_updated_at_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
