# Generated by Django 5.0.4 on 2024-06-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0041_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('SU', 'Supervisor'), ('GE', 'Gestor de Eventos'), ('AD', 'Administrador'), ('US', 'Usuario Estándar')], default='US', max_length=2),
        ),
    ]
