# Generated by Django 5.0.6 on 2024-07-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0064_projectattendee_project_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
