# Generated by Django 5.0.6 on 2024-07-08 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0067_alter_event_attendees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='collaborating_events', through='eventos.EventAttendee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='collaborating_projects', through='eventos.ProjectAttendee', to=settings.AUTH_USER_MODEL),
        ),
    ]
