# Generated by Django 5.0.4 on 2024-05-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_remove_task_project_task_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done',
        ),
    ]
