# Generated by Django 5.0.4 on 2024-05-05 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendee',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventattendee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventAttendee',
        ),
    ]
