# Generated by Django 5.0.4 on 2024-05-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
    ]
