# Generated by Django 5.0.4 on 2024-05-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_remove_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
