# Generated by Django 5.0.4 on 2024-05-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0023_alter_event_ticket_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=2)),
            ],
        ),
    ]
