# Generated by Django 5.0.4 on 2024-05-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0024_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='estado',
            new_name='status_name',
        ),
        migrations.AddField(
            model_name='estado',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
