# Generated by Django 5.0.4 on 2024-05-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0031_alter_event_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.CharField(default='white', max_length=30),
        ),
    ]
