# Generated by Django 5.0.4 on 2024-06-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0037_alter_event_attendees_alter_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendee',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
