# Generated by Django 5.0.4 on 2024-06-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0044_event_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
