# Generated by Django 5.0.6 on 2024-06-24 13:35

import django.core.validators
import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0051_image_alter_document_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(upload_to=eventos.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'ppt'])]),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload',
            field=models.FileField(upload_to=eventos.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'bmp', 'png'])]),
        ),
    ]
