# Generated by Django 5.0.6 on 2024-06-28 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0053_tipificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tipificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.tipificacion'),
        ),
    ]
