# Generated by Django 5.0.6 on 2024-07-08 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0066_taskstatus_alter_project_attendees_taskhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, null=True, related_name='collaborating_events', through='eventos.EventAttendee', to=settings.AUTH_USER_MODEL),
        ),
    ]
