# Generated by Django 5.0.6 on 2024-07-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0069_task_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
