# Generated by Django 5.0.6 on 2024-07-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0074_taskstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
