# Generated by Django 5.0.6 on 2024-07-17 23:01

import django.core.validators
import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0075_remove_task_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to=eventos.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['csv', 'txt', 'xlsx', 'xlsm'])])),
            ],
        ),
    ]
