# Generated by Django 5.0.6 on 2024-07-17 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0076_databases'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Databases',
            new_name='Database',
        ),
    ]
