# Generated by Django 5.0.6 on 2024-07-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0077_rename_databases_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
