# Generated by Django 5.1.7 on 2026-03-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botlog',
            name='category',
            field=models.CharField(choices=[('task', 'Tarea'), ('system', 'Sistema'), ('error', 'Error'), ('communication', 'Comunicación'), ('performance', 'Rendimiento'), ('lead', 'Lead'), ('lead_distribution', 'Distribución de Leads'), ('gtd', 'GTD'), ('coordination', 'Coordinación')], default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Nuevo'), ('assigned', 'Asignado'), ('in_progress', 'En Progreso'), ('contacted', 'Contactado'), ('qualified', 'Calificado'), ('converted', 'Convertido'), ('rejected', 'Rechazado'), ('follow_up', 'Seguimiento'), ('skipped', 'Omitido')], default='new', max_length=50),
        ),
    ]
