# Generated by Django 4.2.16 on 2024-10-23 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('face', models.CharField(choices=[('NORTE', 'Norte'), ('SUR', 'Sur'), ('ESTE', 'Este'), ('OESTE', 'Oeste'), ('ARRIBA', 'Arriba'), ('ABAJO', 'Abajo')], max_length=10)),
                ('type', models.CharField(choices=[('PUERTA', 'Puerta'), ('VENTANA', 'Ventana'), ('SOTANO', 'Sotano'), ('ATICO', 'Ático')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='text',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='altura',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='anchura',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='longitud',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='parent_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='pitch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='roll',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='surface',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('DOBLES', 'Dobles'), ('SUITE', 'Suite')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='yaw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='z',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='permissions',
            field=models.CharField(choices=[('public', 'Pública'), ('private', 'Privada'), ('restricted', 'Restringida')], default='public', max_length=255),
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance', to='rooms.entranceexit')),
                ('exit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit', to='rooms.entranceexit')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
        migrations.AddField(
            model_name='entranceexit',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
    ]
