# Generated by Django 5.1.7 on 2025-04-04 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_cdc_outbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='surface',
            new_name='height',
        ),
        migrations.RemoveField(
            model_name='entranceexit',
            name='type',
        ),
        migrations.RemoveField(
            model_name='portal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portal',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='room',
            name='anchura',
        ),
        migrations.RemoveField(
            model_name='room',
            name='available',
        ),
        migrations.RemoveField(
            model_name='room',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='room',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='room',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.RemoveField(
            model_name='room',
            name='type',
        ),
        migrations.AddField(
            model_name='entranceexit',
            name='position_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entranceexit',
            name='position_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='cooldown',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='portal',
            name='energy_cost',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='portal',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='length',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('OFFICE', 'Office'), ('MEETING', 'Meeting Room'), ('LOUNGE', 'Lounge'), ('KITCHEN', 'Kitchen'), ('BATHROOM', 'Bathroom'), ('SPECIAL', 'Special Area')], default='OFFICE', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='width',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='entranceexit',
            name='face',
            field=models.CharField(choices=[('NORTH', 'North'), ('SOUTH', 'South'), ('EAST', 'East'), ('WEST', 'West'), ('UP', 'Up'), ('DOWN', 'Down')], max_length=10),
        ),
        migrations.AlterField(
            model_name='entranceexit',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='entrance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_entrance', to='rooms.entranceexit'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='exit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_exit', to='rooms.entranceexit'),
        ),
        migrations.AlterField(
            model_name='room',
            name='parent_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_of_rooms', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='permissions',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('restricted', 'Restricted')], default='public', max_length=255),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('energy', models.IntegerField(default=100)),
                ('productivity', models.IntegerField(default=50)),
                ('social', models.IntegerField(default=50)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('WORKING', 'Trabajando'), ('RESTING', 'Descansando'), ('SOCIALIZING', 'Socializando'), ('IDLE', 'Inactivo')], default='IDLE', max_length=20)),
                ('skills', models.JSONField(default=list)),
                ('last_state_change', models.DateTimeField(auto_now=True)),
                ('current_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidirectional', models.BooleanField(default=True)),
                ('energy_cost', models.IntegerField(default=0)),
                ('entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_connections', to='rooms.entranceexit')),
                ('from_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_connections', to='rooms.room')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_connections', to='rooms.room')),
            ],
            options={
                'unique_together': {('from_room', 'to_room', 'entrance')},
            },
        ),
        migrations.AddField(
            model_name='entranceexit',
            name='connection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.roomconnection'),
        ),
        migrations.AddField(
            model_name='room',
            name='connections',
            field=models.ManyToManyField(related_name='connected_to_rooms', through='rooms.RoomConnection', to='rooms.room'),
        ),
        migrations.CreateModel(
            name='RoomObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('object_type', models.CharField(choices=[('WORK', 'Workstation'), ('SOCIAL', 'Social Area'), ('REST', 'Rest Zone'), ('DOOR', 'Door'), ('EQUIPMENT', 'Equipment')], max_length=50)),
                ('effect', models.JSONField(default=dict)),
                ('interaction_cooldown', models.IntegerField(default=60)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='rooms.room')),
            ],
        ),
    ]
