# Generated by Django 5.1.7 on 2025-04-07 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_rename_surface_room_height_remove_entranceexit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='portals',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.portal'),
        ),
        migrations.AlterField(
            model_name='entranceexit',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_exits', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='connections',
            field=models.ManyToManyField(related_name='connected_rooms', through='rooms.RoomConnection', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='roomobject',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_objects', to='rooms.room'),
        ),
    ]
