# Generated by Django 5.1.7 on 2026-03-11 16:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('function_key', models.CharField(max_length=100)),
                ('sources', models.JSONField(default=list)),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Generando'), ('done', 'Listo'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_msg', models.TextField(blank=True)),
                ('result_data', models.JSONField(default=list)),
                ('result_meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoredDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cache_key', models.CharField(max_length=120, unique=True)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('col_count', models.PositiveIntegerField(default=0)),
                ('columns', models.JSONField(default=list)),
                ('dtype_map', models.JSONField(default=dict)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dataset Guardado',
                'verbose_name_plural': 'Datasets Guardados',
                'ordering': ['-created_at'],
            },
        ),
    ]
