# Generated by Django 5.1.7 on 2026-03-11 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0002_storeddataset_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='error_msg',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='function_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='params',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='result_data',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='report',
            name='result_meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='sources',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Generando'), ('done', 'Listo'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='storeddataset',
            name='cache_key',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='storeddataset',
            name='col_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storeddataset',
            name='columns',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='storeddataset',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storeddataset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storeddataset',
            name='dtype_map',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='storeddataset',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='storeddataset',
            name='rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storeddataset',
            name='source_file',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
