# Generated by Django 5.1.7 on 2026-03-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0003_alter_report_created_by_alter_report_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeddataset',
            name='data_blob',
            field=models.TextField(blank=True, default=''),
        ),
    ]
