# Generated by Django 5.1.7 on 2026-03-12 19:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0004_storeddataset_data_blob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('model_path', models.CharField(max_length=200)),
                ('fields', models.JSONField(default=list)),
                ('filters', models.JSONField(default=list)),
                ('date_field', models.CharField(blank=True, max_length=100)),
                ('aggregations', models.JSONField(default=dict)),
                ('sql_override', models.TextField(blank=True)),
                ('chunk_size', models.PositiveIntegerField(default=5000)),
                ('max_rows', models.PositiveIntegerField(default=0, help_text='0 = sin límite')),
                ('frequency', models.CharField(choices=[('manual', 'Manual'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etl_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fuente ETL',
                'verbose_name_plural': 'Fuentes ETL',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ETLJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('runtime_params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('idle', 'Inactivo'), ('running', 'Ejecutando'), ('done', 'Completado'), ('error', 'Error')], default='idle', max_length=20)),
                ('error_msg', models.TextField(blank=True)),
                ('rows_extracted', models.PositiveIntegerField(default=0)),
                ('duration_s', models.FloatField(default=0.0, help_text='Segundos de ejecución')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etl_jobs', to='analyst.storeddataset')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etl_jobs', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='analyst.etlsource')),
            ],
            options={
                'verbose_name': 'Trabajo ETL',
                'verbose_name_plural': 'Trabajos ETL',
                'ordering': ['-created_at'],
            },
        ),
    ]
