# Generated by Django 5.1.7 on 2026-03-13 19:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0006_add_analyst_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etlsource',
            name='analyst_base',
        ),
        migrations.AlterField(
            model_name='analystbase',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
