# Generated by Django 5.1.7 on 2026-03-13 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0007_remove_etlsource_analyst_base_alter_analystbase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlsource',
            name='analyst_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etl_sources', to='analyst.analystbase', verbose_name='Base de datos analista'),
        ),
        migrations.AlterField(
            model_name='etlsource',
            name='model_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
