# Generated by Django 5.1.7 on 2026-03-14 12:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0009_add_cross_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosssource',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
