# Generated by Django 5.1.7 on 2026-02-01 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(verbose_name='Semana')),
                ('agente', models.CharField(max_length=100, verbose_name='Agente')),
                ('supervisor', models.CharField(max_length=100, verbose_name='Supervisor')),
                ('servicio', models.CharField(choices=[('Reclamos', 'Reclamos'), ('Consultas', 'Consultas')], max_length=50, verbose_name='Servicio')),
                ('canal', models.CharField(choices=[('Phone', 'Phone'), ('Mail', 'Mail'), ('Chat', 'Chat')], max_length=50, verbose_name='Canal')),
                ('eventos', models.IntegerField(verbose_name='Eventos')),
                ('aht', models.FloatField(verbose_name='AHT')),
                ('evaluaciones', models.IntegerField(verbose_name='Evaluaciones')),
                ('satisfaccion', models.FloatField(verbose_name='Satisfacción')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Primer día del mes al que corresponde la tasa', verbose_name='Fecha de referencia')),
                ('rate', models.DecimalField(decimal_places=6, help_text='Tasa promedio PEN/USD - Compra interbancaria', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa de cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
    ]
