# Generated by Django 5.1.7 on 2025-03-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(verbose_name='Semana')),
                ('agente', models.CharField(max_length=100, verbose_name='Agente')),
                ('supervisor', models.CharField(max_length=100, verbose_name='Supervisor')),
                ('servicio', models.CharField(choices=[('Reclamos', 'Reclamos'), ('Consultas', 'Consultas')], max_length=50, verbose_name='Servicio')),
                ('canal', models.CharField(choices=[('Phone', 'Phone'), ('Mail', 'Mail'), ('Chat', 'Chat')], max_length=50, verbose_name='Canal')),
                ('eventos', models.IntegerField(verbose_name='Eventos')),
                ('aht', models.FloatField(verbose_name='AHT')),
                ('evaluaciones', models.IntegerField(verbose_name='Evaluaciones')),
                ('satisfaccion', models.FloatField(verbose_name='Satisfacción')),
            ],
        ),
    ]
