# Generated by Django 5.1.7 on 2026-02-13 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='board/covers/')),
                ('layout', models.CharField(choices=[('masonry', 'Masonry Grid'), ('grid', 'Grid Uniforme'), ('free', 'Posición Libre')], default='masonry', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_boards', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'creó'), ('updated', 'actualizó'), ('deleted', 'eliminó'), ('moved', 'movió'), ('pinned', 'fijó')], max_length=20)),
                ('target', models.CharField(max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='board.board')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('note', '📝 Nota'), ('image', '🖼️ Imagen'), ('link', '🔗 Enlace'), ('task', '✅ Tarea'), ('video', '🎬 Video')], default='note', max_length=10)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='board/cards/')),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=1)),
                ('height', models.IntegerField(default=1)),
                ('color', models.CharField(default='white', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='board.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['owner', '-updated_at'], name='board_board_owner_i_49bd60_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['is_public'], name='board_board_is_publ_cbfbe7_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['board', '-timestamp'], name='board_activ_board_i_abc614_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['board', '-created_at'], name='board_card_board_i_4178ca_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['board', 'card_type'], name='board_card_board_i_dfb36b_idx'),
        ),
    ]
