# Generated by Django 5.1.7 on 2026-03-17 21:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0003_add_sim_agent_profile'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='simagent',
            name='unique_agent_per_account',
        ),
        migrations.RenameIndex(
            model_name='interaction',
            new_name='sim_interac_account_416bef_idx',
            old_name='sim_inter_acc_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='interaction',
            new_name='sim_interac_account_da52f3_idx',
            old_name='sim_inter_canal_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='interaction',
            new_name='sim_interac_agent_i_19b364_idx',
            old_name='sim_inter_agent_fecha_idx',
        ),
        migrations.AlterField(
            model_name='simaccount',
            name='preset',
            field=models.CharField(blank=True, help_text='Preset usado: banking_inbound / telco_outbound / banking_digital', max_length=50),
        ),
        migrations.AlterField(
            model_name='simagent',
            name='adherencia_base',
            field=models.FloatField(default=0.931, help_text='Adherencia base 0.0-1.0'),
        ),
        migrations.AlterField(
            model_name='simagent',
            name='sph_base',
            field=models.FloatField(default=0.128, help_text='Sales/ventas por hora base del agente'),
        ),
        migrations.AlterField(
            model_name='simagent',
            name='tmo_factor',
            field=models.FloatField(default=1.0, help_text='Factor sobre TMO base (1.0 = promedio)'),
        ),
        migrations.AlterField(
            model_name='simagentprofile',
            name='acw_factor',
            field=models.FloatField(default=1.0, help_text='Multiplicador sobre ACW base'),
        ),
        migrations.AlterField(
            model_name='simagentprofile',
            name='agenda_rate',
            field=models.FloatField(default=0.128, help_text='Tasa de agendamiento sobre contactos'),
        ),
        migrations.AlterField(
            model_name='simagentprofile',
            name='aht_factor',
            field=models.FloatField(default=1.0, help_text='Multiplicador sobre AHT base del preset (0.85 = 15% más rápido)'),
        ),
        migrations.AlterField(
            model_name='simagentprofile',
            name='answer_rate',
            field=models.FloatField(default=0.95, help_text='Fracción de llamadas que atiende (vs rechaza/deja ring)'),
        ),
        migrations.AlterField(
            model_name='simagentprofile',
            name='available_pct',
            field=models.FloatField(default=0.85, help_text='Fracción de tiempo logueado en estado Available'),
        ),
        migrations.AlterField(
            model_name='simagentprofile',
            name='break_dur_s',
            field=models.IntegerField(default=300, help_text='Duración media del break no programado en segundos'),
        ),
        migrations.AlterField(
            model_name='simagentprofile',
            name='break_freq',
            field=models.FloatField(default=1.0, help_text='Breaks no programados por hora'),
        ),
        migrations.AlterField(
            model_name='simagentprofile',
            name='conv_rate',
            field=models.FloatField(default=0.008, help_text='Tasa de conversión a venta sobre contactos'),
        ),
        migrations.AlterField(
            model_name='simagentprofile',
            name='corte_rate',
            field=models.FloatField(default=0.05, help_text='Fracción de llamadas donde corta antes de finalizar ACW'),
        ),
        migrations.AlterField(
            model_name='simagentprofile',
            name='hold_dur_s',
            field=models.IntegerField(default=30, help_text='Duración media del hold en segundos'),
        ),
        migrations.AlterField(
            model_name='simagentprofile',
            name='hold_rate',
            field=models.FloatField(default=0.05, help_text='Fracción de llamadas que pone en hold'),
        ),
        migrations.AlterField(
            model_name='simagentprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simagentprofile',
            name='is_preset',
            field=models.BooleanField(default=False, help_text='True = preset del sistema (no editable por usuarios)'),
        ),
        migrations.AlterField(
            model_name='simagentprofile',
            name='shrinkage',
            field=models.FloatField(default=0.1, help_text='Fracción de tiempo improductivo total (0.10 = 10%)'),
        ),
        migrations.AlterField(
            model_name='simagentprofile',
            name='skill_priority',
            field=models.JSONField(default=dict, help_text='Prioridad por skill {"PORTABILIDAD": 1, "LINEA NUEVA": 2}'),
        ),
        migrations.AlterField(
            model_name='simagentprofile',
            name='skills',
            field=models.JSONField(default=list, help_text='Skills que puede atender ["PORTABILIDAD", "LINEA NUEVA"]'),
        ),
        migrations.AlterField(
            model_name='simagentprofile',
            name='transfer_rate',
            field=models.FloatField(default=0.04, help_text='Fracción de llamadas que transfiere'),
        ),
        migrations.AlterField(
            model_name='trainingscenario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='simagent',
            unique_together={('account', 'codigo')},
        ),
    ]
