# Generated by Django 5.1.7 on 2026-03-18 02:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0005_add_acd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='acdinteraction',
            new_name='sim_acdinte_session_03abee_idx',
            old_name='sim_acdint_sess_status',
        ),
        migrations.RenameIndex(
            model_name='acdinteraction',
            new_name='sim_acdinte_slot_id_d7de18_idx',
            old_name='sim_acdint_slot_queued',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='gtr_session_id',
        ),
        migrations.AlterField(
            model_name='acdagentaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='acdagentslot',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre para display'),
        ),
        migrations.AlterField(
            model_name='acdagentslot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='acdagentslot',
            name='level',
            field=models.CharField(choices=[('basic', 'Básico'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='basic', max_length=15, verbose_name='Nivel OJT (solo real)'),
        ),
        migrations.AlterField(
            model_name='acdagentslot',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acd_slots', to='sim.simagentprofile', verbose_name='Perfil simulado'),
        ),
        migrations.AlterField(
            model_name='acdagentslot',
            name='skill',
            field=models.CharField(blank=True, max_length=100, verbose_name='Skill activo'),
        ),
        migrations.AlterField(
            model_name='acdagentslot',
            name='slot_number',
            field=models.IntegerField(default=1, verbose_name='Nro. slot'),
        ),
        migrations.AlterField(
            model_name='acdagentslot',
            name='stats',
            field=models.JSONField(default=dict, verbose_name='Métricas acumuladas'),
        ),
        migrations.AlterField(
            model_name='acdagentslot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acd_slots', to=settings.AUTH_USER_MODEL, verbose_name='Usuario OJT'),
        ),
        migrations.AlterField(
            model_name='acdinteraction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='acdsession',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acd_sessions', to='sim.simaccount', verbose_name='Cuenta simulada'),
        ),
        migrations.AlterField(
            model_name='acdsession',
            name='config',
            field=models.JSONField(default=dict, verbose_name='Configuración adicional'),
        ),
        migrations.AlterField(
            model_name='acdsession',
            name='dialing_mode',
            field=models.CharField(choices=[('predictive', 'Predictivo'), ('progressive', 'Progresivo'), ('manual', 'Manual')], default='progressive', max_length=15, verbose_name='Modo de discado'),
        ),
        migrations.AlterField(
            model_name='acdsession',
            name='gtr_session_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID sesión GTR (Redis)'),
        ),
        migrations.AlterField(
            model_name='acdsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='acdsession',
            name='thresholds',
            field=models.JSONField(default=dict, verbose_name='Umbrales de alerta'),
        ),
    ]
