# Generated by Django 5.1.7 on 2025-09-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
