# Generated by Django 5.1.7 on 2026-02-09 21:48

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(choices=[('personal', 'Personal'), ('viaje', 'Viaje'), ('trabajo', 'Trabajo'), ('meta', 'Meta'), ('idea', 'Idea'), ('recuerdo', 'Recuerdo'), ('diario', 'Diario'), ('reflexion', 'Reflexión')], default='personal', max_length=50)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('structured_content', models.JSONField(blank=True, default=list, help_text='Contenido estructurado con elementos de courses')),
                ('is_public', models.BooleanField(default=False)),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.project')),
                ('related_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.task')),
                ('tags', models.ManyToManyField(blank=True, to='events.tag')),
            ],
            options={
                'verbose_name': 'Entrada de Bitácora',
                'verbose_name_plural': 'Entradas de Bitácora',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='bitacora/attachments/')),
                ('tipo', models.CharField(choices=[('image', 'Imagen'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Documento')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bitacora.bitacoraentry')),
            ],
            options={
                'verbose_name': 'Adjunto de Bitácora',
                'verbose_name_plural': 'Adjuntos de Bitácora',
            },
        ),
    ]
