# Generated by Django 5.1.7 on 2026-02-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraentry',
            name='contenido',
            field=models.TextField(),
        ),
    ]
