# Generated by Django 5.1.7 on 2026-05-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0004_uuid_primary_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraentry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
